LeagueOfLegendsUsernameSubmitter/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LeagueOfLegendsUsernameSubmitter.Models
{
    public class Comment
    {
        [Key]
        public int commentId { get; set; }
        public string commentDescription { get; set; }
        public string commentAuthor { get; set; }


       public string Description { get; set; }
       public int id { get; set; }
    }
}

LeagueOfLegendsUsernameSubmitter/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LeagueOfLegendsUsernameSubmitter.Models
{
    public class Player
    {
        [Required]     
        public string SummonerName { get; set; }
        public int id { get; set; }
        public string rank { get; set; }
        
        public string Description { get; set; }
        public DateTime dayposted { get; set; }
        public string region { get; set; }

       

    }
}

LeagueOfLegendsUsernameSubmitter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeagueOfLegendsUsernameSubmitter.Controllers
{
    public class HomeController : Controller
    {
       

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LeagueOfLegendsUsernameSubmitter/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueOfLegendsUsernameSubmitter.Infrastracture;
using LeagueOfLegendsUsernameSubmitter.Models;
using PagedList;
using PusherServer;
using System.Threading.Tasks;

namespace LeagueOfLegendsUsernameSubmitter.Controllers
{
    public class PlayersController : Controller
    {
        private LigaContext db = new LigaContext();

        // GET: Players
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var players = from p in db.Players
                           select p;
            if (!String.IsNullOrEmpty(searchString))
            {
                players = players.Where(p => p.SummonerName.Contains(searchString));
                                       
            }
            switch (sortOrder)
            {
                    case "date_desc":
                    players = players.OrderByDescending(p => p.dayposted);
                    break;
                default:
                    players = players.OrderBy(p => p.dayposted);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(players.ToPagedList(pageNumber, pageSize));
        }

        // GET: Players/Details/5
        public ActionResult Details(int? id)
        {               
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
          


            return View(player);
        }

        // GET: Players/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,SummonerName,rank,Description,dayposted")] Player player)
        {
            if (ModelState.IsValid)
            {
                player.dayposted = DateTime.Now;
                db.Players.Add(player);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(player);
        }

        // GET: Players/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,SummonerName,rank,profilePhoto,Description,dayposted")] Player player)
        {
            if (ModelState.IsValid)
            {
                player.dayposted = DateTime.Now;
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public ActionResult Comments(int? id)
        {
            var comments = db.Comments.Where(x => x.id == id).ToArray();
            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> Comment(Comment data)
        {
            db.Comments.Add(data);
            db.SaveChanges();
            var options = new PusherOptions();
            options.Cluster = "eu";
            var pusher = new Pusher("779904", "f690692a8ba64ca95b50", "d2c9c224e9f6f5efe3fd", options);
            ITriggerResult result = await pusher.TriggerAsync("asp_channel", "asp_event", data);
            return Content("ok");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeagueOfLegendsUsernameSubmitter/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LeagueOfLegendsUsernameSubmitter/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>


<p>Contact us if you have any questions we can address</p>

<address>
    <strong>Support:</strong>   <a href="mailto:fb26288@seeu.edu.mk">fb26288@seeu.edu.mk</a><br />
    <strong>Marketing:</strong> <a href="mailto:fb26288@seeu.edu.mk">fb26288@seeu.edu.mk</a>
</address>

LeagueOfLegendsUsernameSubmitter/Views/Players/Comments.cshtml
@model LeagueOfLegendsUsernameSubmitter.Models.Comment

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.commentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.commentAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.commentAuthor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.commentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeagueOfLegendsUsernameSubmitter/Views/Players/Create.cshtml
@model LeagueOfLegendsUsernameSubmitter.Models.Player

@{
    ViewBag.Title = "Post Username";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Players"))
{
    @Html.AntiForgeryToken()
   

    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SummonerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SummonerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SummonerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rank, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "big" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.dayposted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dayposted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dayposted, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueOfLegendsUsernameSubmitter/Views/Players/Details.cshtml
@model LeagueOfLegendsUsernameSubmitter.Models.Player

@{
    ViewBag.Title = "Details";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.16.2/axios.min.js"></script>
<script src="https://js.pusher.com/4.4/pusher.min.js"></script>
<script>
    var pusher = new Pusher('f690692a8ba64ca95b50', {
        cluster: 'eu'
    });
    var my_channel = pusher.subscribe('asp_channel');
    var app = new Vue({
        el: '#app',
        data: {
            comments: [],
            comment: {
                Name: '',
                Body: '',
                BlogPostID: @Model.id
            }
        },
        created: function() {
            this.get_comments();
            this.listen();
        },
        methods: {
            get_comments: function() {
                axios.get('@Url.Action("Comments", "Home", new { id = Model.id }, protocol: Request.Url.Scheme)')
                    .then((response) => {

                        this.comments = response.data;

                    });

            },
            listen: function() {
                my_channel.bind("asp_event", (data) => {
                    if (data.id == this.comment.id) {
                        this.comments.push(data);
                    }

                })
            },
            submit_comment: function() {
                axios.post('@Url.Action("Comment", "Home", new {}, protocol: Request.Url.Scheme)', this.comment)
                    .then((response) => {
                        this.comment.Name = '';
                        this.comment.Body = '';
                        alert("Comment Submitted");

                    });
            }
        }
    });
</script>
<style>
    .user_name {
        font-size: 14px;
        font-weight: bold;
    }

    .comments-list .media {
        border-bottom: 1px dotted #ccc;
    }
</style>
<h2>Details</h2>

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SummonerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SummonerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dayposted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dayposted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.region)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.region)
        </dd>

    </dl>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="page-header">
                    <h1><small class="pull-right">{{comments.length}} comments</small> Comments </h1>
                </div>
                <div class="comments-list">
                    <div class="media" v-for="com in comments">
                        <div class="media-body">
                            <h4 class="media-heading user_name">{{com.Name}}</h4>
                            {{com.Body}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <br />
        <p>Your Comment</p>
        <form onsubmit="return false;">
            <input type="text" id="Name" placeholder="Your Name" v-model="comment.Name" class="form-control" />
            <textarea rows="3" placeholder="Your Comment" id="Body" v-model="comment.Body" class="form-control"></textarea>
            <button class="btn btn-success" v-on:click="submit_comment()">save</button>
        </form>
    </div>
</div>
<p>
    
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeagueOfLegendsUsernameSubmitter/Views/Players/Edit.cshtml
@model LeagueOfLegendsUsernameSubmitter.Models.Player

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.SummonerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SummonerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SummonerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rank, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dayposted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dayposted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dayposted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeagueOfLegendsUsernameSubmitter/Views/Players/Index.cshtml
@model PagedList.IPagedList<LeagueOfLegendsUsernameSubmitter.Models.Player>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Players";
}

<h2>Players</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Player", FormMethod.Get))
{
    <p>
        Find by Summoner name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Summoner Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
           Date Posted
        </th>
        <th>
            @Html.ActionLink("Date Posted", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.SummonerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dayposted)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

LeagueOfLegendsUsernameSubmitter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - League of Legends username finder</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
	
	
	
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LoL Username Finder", "Index", "Players", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Index", "Index", "Players")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
					<li>@Html.ActionLink("Create", "Create", "Players")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - League of Legends Username Finder</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>